# Avoid SNAPSHOT being frozen by jitpack

name: antifreeze

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "5 3 */5 * *"

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  clear:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Delete Jitpack resource 
      id: jitpack-antifreeze
      env:
        JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
      shell: bash
      run: |
        VERSION=$(./mvnw -B --no-transfer-progress help:evaluate -Dexpression=project.version | grep -v INFO)
        echo $VERSION
        if [[ $VERSION == [.0-9]*-SNAPSHOT ]]; then
          echo "Delete JitPack artifacts for tag"
          curl -X "DELETE" -u${JITPACK_TOKEN} https://jitpack.io/api/builds/dev.ebullient/fc5-convert-cli/$VERSION
        fi
