name: 5e Tools Test
on:
  schedule:
    - cron: "7 9 * * */5"

  workflow_dispatch:

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin
  NATIVE_JAVA_VERSION: 23
  GRAALVM_DIST: graalvm-community
  FAIL_ISSUE: 140

permissions: read-all

jobs:
  metadata:
    uses: ebullient/workflows/.github/workflows/java-snap-metadata.yml@main

  tools5e_cache:
    uses: ./.github/workflows/tools5e-data-cache.yml

  build:
    runs-on: ubuntu-latest
    needs: [tools5e_cache, metadata]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: tools5e-cache-load
        with:
          path: sources
          key: ${{ needs.tools5e_cache.outputs.cache_key }}
          restore-keys: ${{ needs.tools5e_cache.outputs.restore_key }}
          fail-on-cache-miss: true

      - name: Build with Maven
        uses: ebullient/workflows/.github/actions/maven-build@main
        with:
          artifact: ${{ needs.metadata.outputs.artifact }}
          version: ${{ needs.metadata.outputs.snapshot }}
          java-version: ${{ env.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRO }}

  native-build:
    runs-on: ubuntu-latest
    needs: [tools5e_cache, metadata, build]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: tools5e-cache-load
        with:
          path: sources
          key: ${{ needs.tools5e_cache.outputs.cache_key }}
          restore-keys: ${{ needs.tools5e_cache.outputs.restore_key }}
          fail-on-cache-miss: true

      - name: Native build with Maven
        uses: ebullient/workflows/.github/actions/native-build@main
        with:
          artifact: ${{ needs.metadata.outputs.artifact }}
          version: ${{ needs.metadata.outputs.snapshot }}
          native-java-version: ${{ env.NATIVE_JAVA_VERSION }}
          distribution: ${{ env.GRAALVM_DIST }}
          matrix-os: ubuntu-latest

  report-native-build:

    name: Report errors
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [build, native-build]
    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - id: gh-issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ env.FAIL_ISSUE }} --body "[Maven build failed: ${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          gh issue reopen ${{ env.FAIL_ISSUE }}
